# Imports

In [1]:
import pandas as pd
import time
from string_grouper import match_strings
from neo4j import GraphDatabase

In [1]:
pd.set_option('display.max_colwidth', None)
domains = pd.read_csv('../data/splitted_datasets/export_domain.csv', usecols=['uuid','event_id', 'value'])

<ipython-input-1-873fabaa4013>:4: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  dataset_splitter.splitt_datasets()

NameError: name 'pd' is not defined

In [3]:
domains

                                       uuid  event_id               value
0      542e4dde-f900-4b27-b297-06b3950d210b         1       stablehost.us
1      543b7c52-687c-43a9-ab1e-4c6c950d210b         4         java-se.com
2      543b88ad-aa68-420d-bed7-4653950d210b         4          micewe.com
3      543b88ad-d5dc-4b03-9d25-4f19950d210b         4          quonlu.com
4      543b88ad-65dc-4ff8-8079-4c87950d210b         4         arbvisa.com
...                                     ...       ...                 ...
21586  00120351-242f-4731-b45e-4c539306554d      1209  merostomata.online
21587  8225aaff-4ffd-4c21-b3f1-7dda8d90fa10      1209   polyphemus.online
21588  999417c7-1cde-4bf3-bd3b-a16eed575220      1209   scorpiones.online
21589  e8250f87-721e-4289-97d7-ab2f829baeaf      1209     asilidae.online
21590  46d437bb-c69e-481b-b3ca-c5d20b83a2d3      1209    graphiuma.online

[21591 rows x 3 columns]

In [4]:
print('The shape: %d x %d' % domains.shape)
print(domains.head())

The shape: 21591 x 3
                                   uuid  event_id          value
0  542e4dde-f900-4b27-b297-06b3950d210b         1  stablehost.us
1  543b7c52-687c-43a9-ab1e-4c6c950d210b         4    java-se.com
2  543b88ad-aa68-420d-bed7-4653950d210b         4     micewe.com
3  543b88ad-d5dc-4b03-9d25-4f19950d210b         4     quonlu.com
4  543b88ad-65dc-4ff8-8079-4c87950d210b         4    arbvisa.com

# String matching with string_grouper

In [5]:
matches = match_strings(domains['value'], master_id=domains['event_id'])
print(matches)

       left_index          left_value  left_event_id  similarity  \
0               0       stablehost.us              1         1.0
1               1         java-se.com              4         1.0
2               1         java-se.com              4         1.0
3               1         java-se.com              4         1.0
4               2          micewe.com              4         1.0
...           ...                 ...            ...         ...
27456       21586  merostomata.online           1209         1.0
27457       21587   polyphemus.online           1209         1.0
27458       21588   scorpiones.online           1209         1.0
27459       21589     asilidae.online           1209         1.0
27460       21590    graphiuma.online           1209         1.0

       right_event_id         right_value  right_index
0                   1       stablehost.us            0
1                   4         java-se.com            1
2                  36         java-se.com         2041
3                  81         java-se.com         4164
4                   4          micewe.com            2
...               ...                 ...          ...
27456            1209  merostomata.online        21586
27457            1209   polyphemus.online        21587
27458            1209   scorpiones.online        21588
27459            1209     asilidae.online        21589
27460            1209    graphiuma.online        21590

[27461 rows x 7 columns]

### drop combinations with similar events

In [6]:
diff_events_only = matches[matches.left_event_id != matches.right_event_id]
print(diff_events_only)

       left_index               left_value  left_event_id  similarity  \
2               1              java-se.com              4    1.000000
3               1              java-se.com              4    1.000000
11              8                  rnil.am             10    1.000000
13              9        standartnevvs.com             10    1.000000
15             10            novinitie.com             10    1.000000
...           ...                      ...            ...         ...
27121       21282          dotmaingame.com           1189    1.000000
27122       21282          dotmaingame.com           1189    1.000000
27322       21467    onedrive-download.com           1205    0.852418
27415       21547  windows-appstore-en.com           1205    0.840843
27416       21547  windows-appstore-en.com           1205    0.840843

       right_event_id          right_value  right_index
2                  36          java-se.com         2041
3                  81          java-se.com         4164
11                 72              rnil.am         3899
13                 72    standartnevvs.com         3129
15                 72        novinitie.com         2815
...               ...                  ...          ...
27121            1186      dotmaingame.com        21068
27122            1188      dotmaingame.com        21155
27322            1186   idrivedownload.com        21127
27415             155  windowsappstore.net         5294
27416             472  windowsappstore.net        12774

[2262 rows x 7 columns]

# Chose similarity level

In [7]:
mask = diff_events_only["similarity"] < 2.0
df = diff_events_only[mask]
df

,left_index,left_value,left_event_id,similarity,right_event_id,right_value,right_index
2,1,java-se.com,4,1.000000,36,java-se.com,2041
3,1,java-se.com,4,1.000000,81,java-se.com,4164
11,8,rnil.am,10,1.000000,72,rnil.am,3899
13,9,standartnevvs.com,10,1.000000,72,standartnevvs.com,3129
15,10,novinitie.com,10,1.000000,72,novinitie.com,2815
...,...,...,...,...,...,...,...
27121,21282,dotmaingame.com,1189,1.000000,1186,dotmaingame.com,21068
27122,21282,dotmaingame.com,1189,1.000000,1188,dotmaingame.com,21155
27322,21467,onedrive-download.com,1205,0.852418,1186,idrivedownload.com,21127
27415,21547,windows-appstore-en.com,1205,0.840843,155,windowsappstore.net,5294
27416,21547,windows-appstore-en.com,1205,0.840843,472,windowsappstore.net,12774

In [8]:
df = df.drop(columns = ["left_index", "right_index"])
df.head(30)

,left_value,left_event_id,similarity,right_event_id,right_value
2,java-se.com,4,1.000000,36,java-se.com
3,java-se.com,4,1.000000,81,java-se.com
11,rnil.am,10,1.000000,72,rnil.am
13,standartnevvs.com,10,1.000000,72,standartnevvs.com
15,novinitie.com,10,1.000000,72,novinitie.com
18,qov.hu.com,10,1.000000,72,qov.hu.com
20,q0v.pl,10,1.000000,72,q0v.pl
24,natoexhibitionff14.com,10,1.000000,342,natoexhibitionff14.com
26,login-osce.org,10,1.000000,342,log-in-osce.org
28,adobeincorp.com,10,1.000000,857,adobeincorp.com
30,windows-updater.com,10,0.808127,28,wwindowsupdate.com
31,windows-updater.com,10,1.000000,845,windows-updater.com
33,adawareblock.com,10,1.000000,72,adawareblock.com
34,adawareblock.com,10,1.000000,856,adawareblock.com
71,notebookhk.net,18,1.000000,122,notebookhk.net
73,dicemention.com,18,1.000000,19,dicemention.com
74,dicemention.com,18,1.000000,122,dicemention.com
767,dicemention.com,19,1.000000,18,dicemention.com
769,dicemention.com,19,1.000000,122,dicemention.com
1046,ntc0668.com,19,0.827881,508,0668.com
2223,googlecaches.com,21,1.000000,50,googlecaches.com
2231,qoog1e.com,21,1.000000,50,qoog1e.com
2233,webmailgoogle.com,21,1.000000,50,webmailgoogle.com
2246,cisco-users.com,28,1.000000,131,cisco-users.com
2248,wwindowsupdate.com,28,0.808127,10,windows-updater.com
2250,wwindowsupdate.com,28,0.808127,845,windows-updater.com
2279,java-se.com,36,1.000000,4,java-se.com
2281,java-se.com,36,1.000000,81,java-se.com
2366,baatarhuu.com,43,1.000000,157,baatarhuu.com
2400,molnews.net,43,1.000000,157,molnews.net

# Preperation: Create a list of unique event_id's

In [10]:
temp_df = df['left_event_id'].append(df['right_event_id'])
unique_event_nodes = temp_df.drop_duplicates()
unique_event_nodes
unique_event_nodes_list = unique_event_nodes.to_list()
unique_event_nodes_list
print(unique_event_nodes_list)

[4, 10, 18, 19, 21, 28, 36, 43, 50, 51, 69, 70, 72, 73, 74, 81, 84, 91, 93, 94, 96, 100, 101, 107, 111, 117, 118, 122, 128, 129, 131, 142, 155, 157, 161, 162, 169, 170, 171, 172, 174, 185, 187, 208, 216, 239, 246, 248, 274, 284, 289, 291, 294, 296, 298, 299, 308, 309, 312, 313, 315, 317, 320, 321, 324, 325, 326, 327, 328, 330, 331, 338, 339, 342, 343, 345, 346, 347, 348, 350, 352, 353, 354, 355, 364, 365, 371, 384, 385, 386, 388, 389, 395, 397, 400, 402, 403, 404, 408, 409, 410, 411, 412, 413, 415, 416, 417, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 431, 432, 433, 434, 435, 436, 437, 439, 443, 450, 451, 452, 453, 455, 457, 458, 459, 460, 464, 466, 467, 472, 477, 508, 551, 566, 599, 606, 617, 625, 650, 691, 695, 701, 702, 706, 719, 790, 792, 793, 837, 845, 851, 855, 856, 857, 858, 865, 869, 872, 874, 875, 909, 910, 912, 928, 931, 957, 973, 994, 1009, 1025, 1028, 1031, 1032, 1034, 1035, 1074, 1099, 1148, 1149, 1167, 1186, 1187, 1188, 1189, 1205]

In [12]:
len(unique_event_nodes_list)

194

# Create for every unique event_id one node

In [11]:
unique_event_nodes_execution_commands = []

for i in unique_event_nodes_list:
   event_node = "(e:Event {event_id: "+ "'" + str(i) + "'" + "})"
   neo4j_create_statemenet = "CREATE" + event_node
   unique_event_nodes_execution_commands.append(neo4j_create_statemenet)

def execute_transactions(unique_event_nodes_execution_commands):
    data_base_connection = GraphDatabase.driver(uri = "bolt://localhost:7687", auth=("neo4j", "password"))
    session = data_base_connection.session()

    for i in unique_event_nodes_execution_commands:
        session.run(i)

execute_transactions(unique_event_nodes_execution_commands)

# Transform df to a list

In [13]:
list_all= df.values.tolist()
list_all[4]

['novinitie.com', 10, 1.0, 72, 'novinitie.com']

### cypher string creation for neo4j

In [14]:
# i = similarity_list[6]
# event_node1 = "(e1:Event {event_id: "+ "'" + str(i[1]) + "'" + "})"
# relationship = "[:IS_A]"
# ioc = "(i1:IoC {url: "+ "'" + str(i[0]) + "'" + "})"
# similar_to = "[:SIMILAR_TO {similarity: "+ "'" + str(i[2]) + "'" + "}]"
# ioc2 = "(i2:IoC {url: "+ "'" + str(i[4]) + "'" + "})"
# event_node2 = "(e2:Event {event_id: "+ "'" + str(i[3]) + "'" + "})"
#
# neo4j_create_statemenet = event_node1 + "-" + relationship + "->" + ioc + "-" + similar_to + "->" + ioc2 + "<-" + relationship + "-" + event_node2
# print(neo4j_create_statemenet )

# Create relationship between event node and url

In [15]:
#change text if needed in merge_left and merge right: 'URL_IS' and Url, url
url_execution_commands = []

for i in list_all:
  match_left = "MATCH (e1:Event {event_id: "+ "'" + str(i[1]) + "'" + "})"
  match_right = "MATCH (e2:Event {event_id: "+ "'" + str(i[3]) + "'" + "})"
  merge_left = "MERGE (e1)-[:URL_IS]->(u1: Url {url: "+ "'" + str(i[0]) + "'" + "})"
  merge_right = "MERGE (e2)-[:URL_IS]->(u2: Url {url: "+ "'" + str(i[4]) + "'" + "})"
  neo4j_statemenet = match_left + " " + match_right + " " + merge_left + " " + merge_right
  url_execution_commands.append(neo4j_statemenet)

def execute_transactions(url_execution_commands):
    data_base_connection = GraphDatabase.driver(uri = "bolt://localhost:7687", auth=("neo4j", "password"))
    session = data_base_connection.session()

    for i in url_execution_commands:
        session.run(i)

execute_transactions(url_execution_commands)

# Create relationship (similarity) between two urls from two different events

In [16]:
#change text if needed in match_left and match_right: 'URL_IS' and Url, url
url_execution_commands = []
similarity_execution_commands = []

for i in list_all:
    match_left = "MATCH (e1:Event {event_id: "+ "'" + str(i[1]) + "'" + "})-[:URL_IS]->(u1: Url {url: "+ "'" + str(i[0]) + "'" + "})"
    match_right = "MATCH (e2:Event {event_id: "+ "'" + str(i[3]) + "'" + "})-[:URL_IS]->(u2: Url {url: "+ "'" + str(i[4]) + "'" + "})"
    merge = "MERGE (u1)-[:IS_SIMILAR_TO {similar: "+ "'" + str(i[2]) + "'" + "}]->(u2)"
    neo4j_statemenet = match_left + " " + match_right + " " + merge
    similarity_execution_commands.append(neo4j_statemenet)

def execute_transactions(similarity_execution_commands):
    data_base_connection = GraphDatabase.driver(uri = "bolt://localhost:7687", auth=("neo4j", "password"))
    session = data_base_connection.session()

    for i in similarity_execution_commands:
        session.run(i)

execute_transactions(similarity_execution_commands)

# Monitoring sample nodes

In [17]:
mask = df['left_event_id'] == 10
df[mask]

,left_value,left_event_id,similarity,right_event_id,right_value
11,rnil.am,10,1.000000,72,rnil.am
13,standartnevvs.com,10,1.000000,72,standartnevvs.com
15,novinitie.com,10,1.000000,72,novinitie.com
18,qov.hu.com,10,1.000000,72,qov.hu.com
20,q0v.pl,10,1.000000,72,q0v.pl
24,natoexhibitionff14.com,10,1.000000,342,natoexhibitionff14.com
26,login-osce.org,10,1.000000,342,log-in-osce.org
28,adobeincorp.com,10,1.000000,857,adobeincorp.com
30,windows-updater.com,10,0.808127,28,wwindowsupdate.com
31,windows-updater.com,10,1.000000,845,windows-updater.com
33,adawareblock.com,10,1.000000,72,adawareblock.com
34,adawareblock.com,10,1.000000,856,adawareblock.com

In [18]:
mask = df['left_event_id'] == 72
df[mask]

,left_value,left_event_id,similarity,right_event_id,right_value
2966,caciltd.com,72,1.000000,845,caciltd.com
2985,mailpho.com,72,1.000000,857,mailpho.com
3062,mfapress.com,72,1.000000,845,mfapress.com
3154,novinitie.com,72,1.000000,10,novinitie.com
3183,tolonevvs.com,72,1.000000,342,tolonevvs.com
3383,adawareblock.com,72,1.000000,10,adawareblock.com
3385,adawareblock.com,72,1.000000,856,adawareblock.com
3388,azureon-line.com,72,1.000000,174,azureon-line.com
3389,azureon-line.com,72,1.000000,845,azureon-line.com
3427,msonlinelive.com,72,1.000000,845,msonlinelive.com
3430,nvidiaupdate.com,72,1.000000,865,nvidiaupdate.com
3437,privacy-live.com,72,1.000000,73,privacy-live.com
3510,googlesetting.com,72,1.000000,324,googlesetting.com
3595,standartnevvs.com,72,1.000000,10,standartnevvs.com
3764,servicesupdates.com,72,0.870972,1186,topservicesupdates.com
3765,servicesupdates.com,72,0.832444,1186,servicesupdater.com
3766,servicesupdates.com,72,0.832444,1188,servicesupdater.com
3767,servicesupdates.com,72,0.832444,1189,servicesupdater.com
3776,aseanchannelnews.com,72,1.000000,325,aseanchannelnews.com
3795,militaryexponews.com,72,1.000000,155,militaryexponews.com
4134,driversupdate.info,72,1.000000,472,driversupdate.info
4142,drivers-update.info,72,1.000000,472,driversupdate.info
4167,microsofthelpcenter.info,72,1.000000,155,microsofthelpcenter.info
4168,microsofthelpcenter.info,72,1.000000,472,microsofthelpcenter.info
4176,1oo7.net,72,1.000000,155,1oo7.net
4177,1oo7.net,72,1.000000,472,1oo7.net
4180,aopg.net,72,1.000000,325,aopg.net
4187,kaliex.net,72,1.000000,371,kaliex.net
4188,kaliex.net,72,1.000000,865,kaliex.net
4281,qov.hu.com,72,1.000000,10,qov.hu.com
4471,mfapress.org,72,1.000000,845,mfapress.org
4478,armypress.org,72,1.000000,845,armypress.org
4561,rnil.am,72,1.000000,10,rnil.am
4623,politicalreview.eu,72,1.000000,472,politicalreview.eu
4678,q0v.pl,72,1.000000,10,q0v.pl
4686,icloudmail.ru,72,0.839739,291,mycloud-mail.ru
4692,mycloudmail.ru,72,1.000000,291,mycloud-mail.ru
4695,setting-mail.ru,72,1.000000,291,setting-mail.ru

In [19]:
mask = df['left_event_id'] == 96
df[mask]

,left_value,left_event_id,similarity,right_event_id,right_value
4991,sharepoint-vaeit.com,96,1.0,51,sharepoint-vaeit.com
4994,sinmoung.com,96,1.0,100,sinmoung.com
4995,ssl-vaeit.com,96,1.0,51,ssl-vaeit.com
4998,topsec2014.com,96,1.0,51,topsec2014.com
5002,wiki-vaeit.com,96,1.0,51,wiki-vaeit.com

In [20]:
mask = df['left_event_id'] == 70
df[mask]

      left_value  left_event_id  similarity  right_event_id right_value
2730  jpaols.com             70         1.0              69  jpaols.com